name: Dispatch

on: [pull_request, create]

jobs:
  dispatch:
    name: Repository Dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to loterie
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: github.com/sameo/loterie
          event-type: hasard-pull-request
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}
